### PR TITLE
Export Tracking so it can be consumed on it's own

### PR DESCRIPTION
**Pull request by robsquires**

### CODE REVIEW

**Comment by notlee** [comment]
Passing `o-tracking` straight through could make upgrading a future major release of `o-audio` difficult in the future, as we would also need to be aware of the whole `o-tracking` api.

Why is `o-tracking` passed through?

**Comment by notlee** [comment]
Approved but, thinking about it, are you not able to import from the `src/tracking.js` without this?

**Comment by robsquires** [comment]
thx! Yeah I have to import `@financial-times/o-audio/dist/js/tracking`, which has a bit of a weird knock on effect on jest mocks.

**Comment by robsquires** [comment]
+ generally feels a bit brittle, file names could change within o-audio + it would become a breaking change

**Pull request merged**
